server:
  port: 9090
## MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atm
    username: root
    password: root

  #`hibernate_sequence' doesn't exist
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  # drop n create table, good for testing, comment this in production
      ddl-auto: create
